/**
 * @fileoverview App type definitions.
 *
 * Entity types (database row shapes) are auto-generated by stellar-drive
 * from the schema definition in `src/lib/schema.ts`. This file re-exports
 * them and adds app-specific narrowings and composite types.
 *
 * To update entity types, edit `src/lib/schema.ts` and save — the Vite
 * plugin regenerates `types.generated.ts` automatically.
 *
 * If a generated type uses `string` where your app needs a narrower union
 * (e.g. `'active' | 'archived'`), use the Omit + extend pattern:
 *
 *   import type { Item as GenItem } from './types.generated';
 *   export type ItemStatus = 'active' | 'archived';
 *   export interface Item extends Omit<GenItem, 'status'> {
 *     status: ItemStatus;
 *   }
 *
 * Similarly for `json` fields (`unknown` in generated types):
 *
 *   export interface Item extends Omit<GenItem, 'metadata'> {
 *     metadata: { tags: string[] } | null;
 *   }
 */

// Re-export stellar-drive utility types
export type { SyncStatus, AuthMode, OfflineCredentials } from 'stellar-drive/types';

// Re-export all generated entity types (override individual ones below as needed)
// export type { MyTable } from './types.generated';

// =============================================================================
//  Note Entity
// =============================================================================

/** A note entity — metadata stored in the sync engine (Supabase Postgres). */
export interface Note {
  [key: string]: unknown;
  id: string;
  title: string;
  icon: string | null;
  parent_note_id: string | null;
  order: number;
  last_edited_at: string;
  last_edited_by: string | null;
  created_by: string | null;
  is_locked: boolean;
  is_trashed: boolean;
  is_offline: boolean;
  created_at: string;
  updated_at: string;
  deleted: boolean;
}

// =============================================================================
//  Comment Entity
// =============================================================================

/** A comment associated with a highlighted text range in a note. */
export interface NoteComment {
  [key: string]: unknown;
  id: string;
  note_id: string;
  content: string;
  quote: string | null;
  mark_id: string;
  resolved: boolean;
  created_at: string;
  updated_at: string;
  deleted: boolean;
}
